# Generated by Django 3.2.7 on 2021-10-27 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_shop_name'),
        ('user', '0005_auto_20211011_1525'),
        ('affiliation', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='related_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='affiliation',
            unique_together={('affiliator', 'related_shop')},
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('base_order_id', 'related_affiliation')},
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='related_product',
        ),
    ]
