# Generated by Django 3.2.7 on 2021-10-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('affiliation', '0004_order_related_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
    ]
