# Generated by Django 3.2.7 on 2021-10-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_product_visibility_product_visibility'),
        ('affiliation', '0006_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='orders', to='product.Product'),
        ),
    ]
