# Generated by Django 3.2.7 on 2021-11-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0007_alter_order_related_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('on-hold', 'on-hold'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('refunded', 'refunded'), ('failed', 'failed'), ('trash', 'trash')], default='pending', max_length=50),
        ),
    ]
