# Generated by Django 3.2.7 on 2021-11-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_shop_url'),
        ('category', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('base_id', 'related_shop')},
        ),
    ]
