# Generated by Django 3.2.7 on 2021-12-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_shop_url'),
        ('category', '0003_auto_20211101_1926'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('base_id', 'related_shop', 'slug')},
        ),
    ]
