# Generated by Django 3.2.7 on 2021-10-28 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0003_auto_20211027_1801'),
        ('financial', '0004_auto_20211010_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='realted_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='affiliation.order'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_state',
            field=models.CharField(choices=[('deposit', 'deposit'), ('received', 'received')], default='pending', max_length=50),
        ),
    ]
