# Generated by Django 3.2.7 on 2021-10-28 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_auto_20211028_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='realted_order',
            new_name='related_order',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
    ]
