# Generated by Django 3.2.7 on 2021-10-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_alter_transaction_related_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
