# Generated by Django 3.2.7 on 2021-10-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_transaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
