# Generated by Django 3.2.7 on 2021-10-30 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0007_alter_order_related_products'),
        ('financial', '0011_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='related_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='affiliation.order'),
        ),
    ]
