# Generated by Django 3.2.7 on 2021-11-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0012_alter_transaction_related_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
