# Generated by Django 3.2.7 on 2021-11-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0013_alter_wallet_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
