# Generated by Django 3.2.7 on 2021-10-28 20:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_shop_name'),
        ('product', '0002_alter_product_related_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='affiliate_rate',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='related_shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.shop'),
        ),
    ]
