# Generated by Django 3.2.7 on 2021-11-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_shop_url'),
        ('product', '0006_alter_product_categories'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('base_id', 'related_shop')},
        ),
    ]
