# Generated by Django 3.2.7 on 2021-11-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
